name: CI/CD PIPELINE    
on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    # revisar si es mejor usar pip install
    - name: Instalar uv
      run: pip install uv

    
    - name: Instalar dependencias
      run: uv sync --frozen

    
    - name: Ejecutar ruff
      run: uv run ruff check --fix .

    
    - name: Ejecutar pruebas con pytest
      run: uv run pytest


    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
    - name: Construir y publicar imagen Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Reemplaza 'tu-usuario' con tu nombre de cuenta en Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/solemne-1:latest
